/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ingress;
@org.apache.avro.specific.AvroGenerated
public enum WebChannelBrand implements org.apache.avro.generic.GenericEnumSymbol<WebChannelBrand> {
  MSK, SEA, MLL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"WebChannelBrand\",\"namespace\":\"com.maersk.notification.avro.ingress\",\"symbols\":[\"MSK\",\"SEA\",\"MLL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
